version: "3.9"
services:
  backend:
    build: ./turf-booking-backend
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=turfdb
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  frontend:
    build: ./turf-booking-frontend
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=turfdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
