name: Build Backend Image
on:
  push:
    paths:
      - 'turf-backend/**'
      - '.github/workflows/backend-build.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          context: ./turf-backend
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/turf-backend:latest
